# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc002da8244520f36146dc6b53739810a88116bb3f6c1c3c7421844a21af1e3c8d5b771f1829fb7090694aba7ab18fd76c79c45b033a44c636134cee65a3142

test:
  secret_key_base: b659e47464c8f06dabf1d9ee3d340747af33e101538e23bfbfad5f51bb3cc7ac32cebaa394c86a03ddec502a2f5bd10e42838e4b21bdd946414b0c2a49128d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
